import axios from 'axios';

class Network {
  constructor() {
    this.baseURL = 'http://localhost:3003';
    this.headers = {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${localStorage.getItem('jwt')}`,
    };
  }

  async get(uri) {
    try {
      const response = await axios.get(`${this.baseURL}${uri}`, {
        headers: this.headers,
      });
      return this.response(200, response.data, 'GET OK', null);
    } catch (error) {
      return this.response(500, null, null, JSON.stringify(error));
    }
  }

  async post(uri, body) {
    try {
      const response = await axios.post(`${this.baseURL}${uri}`, body, {
        headers: this.headers,
      });
      return this.response(200, response.data, 'GET OK', null);
    } catch (error) {
      return this.response(500, null, null, JSON.stringify(error));
    }
  }

  response(code = null, data = null, message = null, error = null) {
    return {
      code: code || 500,
      message: message || 'Internal Server Error',
      data: data || {},
      error:
        code === 200
          ? null
          : error ||
            'An error occured with an exception within the Network class.',
    };
  }
}

export default Network;
